Maak weer installeerbaar

diff --git a/debian/pkgtemplates/flavours.init b/debian/pkgtemplates/flavours.init
--- a/debian/pkgtemplates/flavours.init
+++ b/debian/pkgtemplates/flavours.init
@@ -5,6 +5,10 @@
 # The variables below are NOT to be changed.  They are there to make the
 # script more readable.
 
+set -e
+
+. /lib/lsb/init-functions
+
 NAME=@FLAVOUR@
 DAEMON=/usr/sbin/$NAME
 PIDFILE=/var/run/$NAME.pid
@@ -14,8 +18,6 @@ APACHECTL=/usr/sbin/${NAME}ctl
 SSD=`which start-stop-daemon`
 ENV="env -i LANG=C PATH=/bin:/usr/bin:/usr/local/bin"
 
-trap "" 1
-
 # Check that we're not being started by inetd
 if egrep -q -i "^[[:space:]]*ServerType[[:space:]]+inet" $CONF
 then
@@ -24,8 +26,8 @@ fi
 
 test_config() {
     if [ ! -x $APACHECTL ]; then
-	echo "$APACHECTL is not executable, exiting"
-	exit 0
+	log_begin_msg "$APACHECTL is not executable, exiting..."
+	log_end_msg 1
     fi
 
     # ensure we don't leak environment vars into apachectl
@@ -33,16 +35,16 @@ test_config() {
 
     if ! $APACHECTL configtest 2> /dev/null
     then
-        printf "Configuration syntax error detected. Not reloading.\n\n"
-        $APACHECTL configtest
-        exit 1
+        log_begin_msg "Configuration syntax error detected, not starting/reloading..."
+        [ "$VERBOSE" != "no" ] && echo "" && $APACHECTL configtest || true
+        log_end_msg 1
     fi
 }
 
 should_start() {
     if [ ! -x $DAEMON ]; then
-	echo "@FLAVOUR@ is not executable, not starting"
-	exit 0
+	log_begin_msg "$DAEMON is not executable, not starting/reloading..."
+	log_end_msg 1
     fi
 }
 
@@ -50,35 +52,61 @@ case "$1" in
   start)
     should_start
     test_config
-    echo -n "Starting web server: $NAME"
-    $ENV $SSD --start --pidfile $PIDFILE --exec $DAEMON > /dev/null
+    log_begin_msg "Starting $NAME 1.3 web server..."
+    if $ENV $SSD --start --pidfile $PIDFILE --exec $DAEMON --oknodo > /dev/null; then
+      log_end_msg 0
+    else
+      log_end_msg 1
+    fi
     ;;
 
   stop)
-    echo -n "Stopping web server: $NAME"
-    start-stop-daemon --stop --pidfile $PIDFILE --oknodo
-    rm -rf /var/lib/apache/mod-bandwidth/link/*
+    log_begin_msg "Stopping $NAME 1.3 web server..."
+    if $ENV $SSD --stop --pidfile $PIDFILE --oknodo; then
+      rm -rf /var/lib/apache/mod-bandwidth/link/*
+      log_end_msg 0
+    else
+      rm -rf /var/lib/apache/mod-bandwidth/link/*
+      log_end_msg 1
+    fi
     ;;
 
   reload | force-reload)
     test_config
-    echo -n "Reloading $NAME configuration"
-    start-stop-daemon --stop --pidfile $PIDFILE --signal USR1
+    log_begin_msg "Reloading $NAME 1.3 configuration..."
+    if $ENV $SSD --stop --pidfile $PIDFILE --signal USR1 --oknodo > /dev/null; then
+      log_end_msg 0
+    else
+      log_end_msg 1
+    fi
     ;;
 
   reload-modules)
-    test_config
-    echo -n "Reloading $NAME modules"
-    start-stop-daemon --stop --pidfile $PIDFILE --oknodo --retry 30
     should_start
-    $ENV $SSD --start --pidfile $PIDFILE --exec $DAEMON > /dev/null
+    test_config
+    log_begin_msg "Reloading $NAME 1.3 modules..."
+    if start-stop-daemon --stop --pidfile $PIDFILE --oknodo --retry 30; then
+      if $ENV $SSD --start --pidfile $PIDFILE --exec $DAEMON > /dev/null; then
+        log_end_msg 0
+      else
+        log_end_msg 1
+      fi
+    else
+      log_end_msg 1
+    fi
     ;;
 
   restart)
     test_config
-    echo -n "Restarting $NAME"
+    log_begin_msg "Restarting $NAME 1.3 web server..."
     if ! start-stop-daemon -q --stop --pidfile $PIDFILE --signal HUP; then
-	$ENV $SSD --start --pidfile $PIDFILE --exec $DAEMON > /dev/null
+      if $ENV $SSD --start --pidfile $PIDFILE --exec $DAEMON --oknodo > /dev/null; then
+        log_end_msg 0
+      else
+        log_end_msg 1
+      fi
+    else
+      log_end_msg 0
     fi
     ;;
 
@@ -88,10 +116,3 @@ case "$1" in
     ;;
 esac
 
-if [ $? -eq 0 ]; then
-	echo .
-	exit 0
-else
-	echo " failed"
-	exit 1
-fi
